### ISSUE TITLE
Release ffscrapr 1.4.8

### ISSUE THREAD

**Issue by tanho63** [ffverse/ffscrapr#384]
Ideally release by end of Nov to facilitate dev-purrr release by Dec 19: https://github.com/ffverse/ffscrapr/pull/383#issuecomment-1309380123

Issues to resolve by 1.4.8:

- [x] fix vec_depth issue changed by dev purrr #383 
- [x] sleeper_draftpicks #352
- [ ] update test infra to piggyback #372 
- [x] loosen hardcoded week in sleeper scoring/leagues #382 

Prepare for release:

* [ ] `usethis::use_version('patch')`
* [ ] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_ffscrapr.html)
* [ ] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [ ] `devtools::build_readme()`
* [ ] `urlchecker::url_check()`
* [ ] `devtools::check(remote = TRUE, manual = TRUE)`
* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] Update `cran-comments.md`

Submit to CRAN:

* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version()`
